### ISSUE TITLE
There should be a way to keep original properties from the mocked class

### ISSUE THREAD

**Issue by DmitryEfimenko** [hirezio/auto-spies#82]
**Is your feature request related to a problem? Please describe.**
Creating a spy from class with observable properties, some of which represent derived state, is not very dev-friendly.

**Describe the solution you'd like**
Please see example below:
```ts
class ProductsService {
  // this is a property that we want to mock since we don't want the unit test to depend on HttpClient
  productsRequest$ = this.http.get('/api/products').pipe(shareReplay(1));

  // we don't want to mock this property. This is simply derived state. We want it to behave just like it used to
  pendingProducts$ = this.productsRequest$.pipe(
    map((products => products.filter(x => x.status === 'pending'))
  );

  constructor(private http: HttpClient) {}
}

// create spy mocking just the property we want to mock
const productsServiceSpy = createSpyFromClass(ProductsService, {
  observablePropsToSpyOn: ['productsRequest$']
});

// example of test
it('should...', () => {
  let actual: Product[] | undefined;

  // the expectation is that this will just work. However, pendingProducts$ is `undefined`
  productsServiceSpy.pendingProducts$.subscribe((res) => {
    actual = res;
  });

  productsServiceSpy.productsRequest$.nextWith([ /* some products */]);

  expect(actual.length).toEqual(5);
})
```

**Describe alternatives you've considered**
* The properties could simply be copied from the prototype of the original class. However, in this case we're running into an issue of mocked classes still depending on some other deps
* There could be a new options flag that would allow to keep certain properties in which case they will be copied from class prototype

**Comment by shairez** [comment]
It's not really possible to preserve it because:
1. We're not using the original instance
2. We can't get the properties from the class

What about using [this instead](https://github.com/hirezio/auto-spies/tree/master/packages/jasmine-auto-spies#-createobservablewithvalues---create-a-pre-configured-standalone-observable)?

**Comment by DmitryEfimenko** [comment]
Can we use the original instance instead of constructing an object from the ground up?

**Comment by shairez** [comment]
That's not the point of this library.
Keeping the original class will require more memory to be used in the tests themselves (instead of creating a lean, side effect free version of their API only).

If you want to keep the the original class, you can fake specific parts on the real instance (though I wouldn't recommend it)

**Comment by DmitryEfimenko** [comment]
sounds good. Thanks for the replies. Closing the issue
